name: test Path

on: workflow_dispatch

jobs:
  prepare:
    name: Pre-flight checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Display version
        shell: pwsh
        run: |
          cd "/usr/share/"
          ls -d az_* 
